server:
 port: 8081

spring:
  application:
    name: auth-service

  datasource:
   url: jdbc:postgresql://localhost:5432/mediflow_auth
   driver-class-name: org.postgresql.Driver
   username: postgres
   password: PgAdmin@123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: ${JWT_SECRET:12345678901234hjkouyqwtyeuahdbekw}

eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
